ManifestType: "installer"
ManifestVersion: "1.0.0"
PackageIdentifier: "DakshSharma.chase"
PackageVersion: "1.0.0"
Platform: 
  - "Windows.Desktop"
InstallModes:
  - "interactive"
  - "silent"
  - "silentWithProgress"
Installers:
  - Architecture: "x64"
    InstallerType: "exe"
    InstallerUrl: "https://github.com/frypan05/chase/releases/download/v1.0.0-alpha/Chase.exe"
    InstallerSha256: "D9DE5BBC59AE78A7EBEF06F47629B9E77BB5DDF57F8BFAE3F5F894FF9C335CEA"
    InstallerLocale: "en-US"
    UpgradeBehavior: "install"
    Dependencies:
      WindowsFeatures: []
      WindowsLibraries: []
      PackageDependencies: []
    InstallerSwitches:
      Silent: "/S"
      SilentWithProgress: "/S"