PackageIdentifier: "DakshSharma.chase"
PackageVersion: "1.0.0"
Platform: 
  - "Windows.Desktop"
ManifestVersion: "1.0.0"
InstallModes:
  - "interactive"
  - "silent"
  - "silentWithProgress"
Installers:
  - Architecture: "x64"
    InstallerType: "exe"
    InstallerUrl: "https://github.com/frypan05/chase/releases/download/v1.0.0/chase.exe"
    InstallerSha256: "d349ed54ae4e077f0605db9e1b236ad62ee1a2259c82e29f0e0d9913096799be"
    InstallerLocale: "en-US"
    UpgradeBehavior: "install"
ManifestType: "installer"
ManifestVersion: "1.0.0"
