ManifestType: "installer"
ManifestVersion: "1.0.0"
PackageIdentifier: "DakshSharma.chase"
PackageVersion: "1.0.0"
Platform: 
  - "Windows.Desktop"
InstallModes:
  - "interactive"
  - "silent"
  - "silentWithProgress"
Installers:
  - Architecture: "x64"
    InstallerType: "exe"
    InstallerUrl: "https://github.com/frypan05/chase/releases/download/v1.0.0/chase.exe"
    InstallerSha256: "1d681c98b85e0e8db64f2e83fa5232f142e2bb75b0a37fd3fe91d84d348f63d4"
    InstallerLocale: "en-US"
    UpgradeBehavior: "install"
    Dependencies:
      - Package: "libcurl-x64.dll"
      - InstallerUrl: "https://github.com/frypan05/chase/releases/download/v1.0.1/libcurl-x64.dll"
      - InstallerSha256: "C9A922CEE3A9A3913DB087BF395683A86C87085F2BDA6092A0E6E543067420BD"
    InstallerSwitches:
      Silent: "/S"
      SilentWithProgress: "/S"