PackageIdentifier: chase.cli
PackageVersion: 1.0.0
ManifestVersion: 1.0.0
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerType: exe
    InstallerUrl: https://github.com/frypan05/chase/manifests/c/chase/chase.cli/1.0.0/cli.exe
    InstallerSha256: 288e5f6537f1a90c0cce2fce8e617dc31abaa25afde6f9782f00efefe026f500
    InstallerLocale: en-US
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
