Id: chase
Name: Chasing Cosmos
Publisher: Daksh Sharma
Version: 1.0.0
Description:  A simple command-line application that provides you relevant research paper analysis from different sites right from your terminal.
License: MIT
Installers:
  - Arch: x64
    InstallerType: exe
    Url: https://github.com/frypan05/chase/manifests/c/chase/chase.cli/1.0.0/cli.exe
    Sha256: 288e5f6537f1a90c0cce2fce8e617dc31abaa25afde6f9782f00efefe026f500
